// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFuMPhid6UuJYFbpYdyJRMaCSSao_OE_Y',
    appId: '1:1040264039772:android:e73472790eb40c69c44599',
    messagingSenderId: '1040264039772',
    projectId: 'promcheckapp',
    storageBucket: 'promcheckapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuCRCJyKQ9GEo9QYhbhlHbTL8LVH5iZQg',
    appId: '1:1040264039772:ios:817a11eb12016c80c44599',
    messagingSenderId: '1040264039772',
    projectId: 'promcheckapp',
    storageBucket: 'promcheckapp.appspot.com',
    iosClientId: '1040264039772-uu86af6oaf91pbhgrfv3u6r6govsh3h0.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
